// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Xb9m645OIb4OKZYF6Ej_wlbu6M2xyDo',
    appId: '1:1061472551918:web:b60234328e1437e73b44ff',
    messagingSenderId: '1061472551918',
    projectId: 'points-bacc9',
    authDomain: 'points-bacc9.firebaseapp.com',
    storageBucket: 'points-bacc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXKZsCRLFVs2AtbktLvVYOszaEVJLZpE',
    appId: '1:1061472551918:android:63cd535816aae90a3b44ff',
    messagingSenderId: '1061472551918',
    projectId: 'points-bacc9',
    storageBucket: 'points-bacc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBiiFt7CkZiqQPrLD1WjFR9r1nZRnCWeQ',
    appId: '1:1061472551918:ios:e83fcd847f7d261b3b44ff',
    messagingSenderId: '1061472551918',
    projectId: 'points-bacc9',
    storageBucket: 'points-bacc9.appspot.com',
    iosBundleId: 'com.example.points',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBiiFt7CkZiqQPrLD1WjFR9r1nZRnCWeQ',
    appId: '1:1061472551918:ios:e83fcd847f7d261b3b44ff',
    messagingSenderId: '1061472551918',
    projectId: 'points-bacc9',
    storageBucket: 'points-bacc9.appspot.com',
    iosBundleId: 'com.example.points',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Xb9m645OIb4OKZYF6Ej_wlbu6M2xyDo',
    appId: '1:1061472551918:web:1aea57e82b9a7a433b44ff',
    messagingSenderId: '1061472551918',
    projectId: 'points-bacc9',
    authDomain: 'points-bacc9.firebaseapp.com',
    storageBucket: 'points-bacc9.appspot.com',
  );

}